name: Build and test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3.0.2
        id: yarn-cache
        with:
          path: |
            node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          ADBLOCK: true

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Check the distributive TypeScript declarations
        run: yarn check:dts

      - name: Check the ability to work with server side rendering
        run: yarn check:ssr

      - name: Build console
        run: yarn build:console

      - name: Build test bundle
        run: yarn build:test

      - name: Test on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: yarn test:browserstack
